//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tokens
    {
        public string Token { get; set; }
        public string Employee_Login { get; set; }
        public Nullable<System.DateTime> Creation_Time { get; set; }
        public Nullable<System.DateTime> End_time { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
